{% set name = "pyrams" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrams-{{ version }}.tar.gz
  sha256: 6aa3665265613e4fbdf4299dfad75eb221c6853bb85516c6b49dc9bcc8cceb9e 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cartopy
    - matplotlib-base
    - metpy
    - netcdf4
    - numpy
    - pandas
    - python >=3.6
    - shapely
    - tqdm
    - xarray >=v2022.03.0
    - cf-xarray >=0.7.4
    - pint >=0.18
    - pint-xarray >=0.3

test:
  imports:
    - pyrams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsterzinger/pyrams
  summary: Set of tools for working with RAMS model data. Documentation can be found here https://pyrams.readthedocs.io/en/stable/?badge=stable
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsterzinger
