{% set name = "pyrams" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrams-{{ version }}.tar.gz
  sha256: 41abbfda182b800b882195d0a0584804703248879d05c4a4276f1f71858e487d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cartopy
    - matplotlib-base
    - metpy
    - netcdf4
    - numpy
    - pandas
    - python >=3.6
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - pyrams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsterzinger/pyrams
  summary: Set of tools for working with RAMS data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsterzinger
