{% set name = "pyrams" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrams-{{ version }}.tar.gz
  sha256: 154eab3aaca101d78c0ff91e748407b973c7b0a8ecbfe3343aa61dcac8db2e7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cartopy
    - matplotlib-base
    - metpy
    - netcdf4
    - numpy
    - pandas
    - python >=3.6
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - pyrams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsterzinger/pyrams
  summary: Set of tools for working with RAMS model data. Documentation can be found here https://pyrams.readthedocs.io/en/stable/?badge=stable
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsterzinger
